# Generated by Django 5.2.4 on 2025-08-23 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(db_index=True, max_length=50)),
                ('input_raw_materials', models.DecimalField(decimal_places=2, max_digits=10)),
                ('output_products', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumables_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_input', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_output', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved')], db_index=True, default='DRAFT', max_length=20)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='inventory.machine')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='inventory.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExportedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel')], max_length=10)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('exported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='reports.productionreport')),
            ],
        ),
        migrations.CreateModel(
            name='ReportAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('APPROVE', 'Approve')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='reports.productionreport')),
            ],
        ),
        migrations.AddIndex(
            model_name='productionreport',
            index=models.Index(fields=['job_number'], name='reports_pro_job_num_73c3fd_idx'),
        ),
        migrations.AddIndex(
            model_name='productionreport',
            index=models.Index(fields=['status'], name='reports_pro_status_f27ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='productionreport',
            index=models.Index(fields=['created_at'], name='reports_pro_created_775133_idx'),
        ),
    ]
