# Generated by Django 5.2.5 on 2025-08-31 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_materialrequest'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreport',
            name='finished_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem'),
            preserve_default=False,
        ),
    ]
