# Generated by Django 5.2.4 on 2025-08-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreport',
            name='waste',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
