# Generated by Django 5.2.5 on 2025-08-31 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_materialrequest'),
        ('reports', '0002_productionreport_finished_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionreport',
            name='finished_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem'),
        ),
    ]
