# Generated by Django 5.2.4 on 2025-08-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_productionreport_waste'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreport',
            name='quantity_produced',
            field=models.IntegerField(default=0),
        ),
    ]
