# Generated by Django 5.2.4 on 2025-08-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_productionreport_quantity_produced'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreport',
            name='downtime_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
