# Generated by Django 5.2.5 on 2025-09-01 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_materialrequest'),
        ('reports', '0003_alter_productionreport_finished_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialconsumption',
            name='raw_item',
        ),
        migrations.AddField(
            model_name='materialconsumption',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialconsumption',
            name='quantity_used',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='materialconsumption',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='reports.productionreport'),
        ),
    ]
