# Generated by Django 5.2.5 on 2025-09-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_materialconsumption_raw_item_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialConsumption',
        ),
    ]
