# Generated by Django 5.2.4 on 2025-08-23 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_productionreport_downtime_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Flexography', 'Flexography'), ('Rotogravure', 'Rotogravure'), ('Slitter Rew1', 'Slitter Rew1'), ('Slitter Rew2', 'Slitter Rew2'), ('Sleeving Machine', 'Sleeving Machine'), ('Sleeve Insp', 'Sleeve Insp')], max_length=100, null=True)),
                ('custom_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.machine'),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.section'),
        ),
    ]
