# Generated by Django 5.2.5 on 2025-09-03 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_delete_materialconsumption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportaudittrail',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportaudittrail',
            name='change_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('CONSUMPTION_CREATE', 'Consumption Created'), ('CONSUMPTION_UPDATE', 'Consumption Updated'), ('CONSUMPTION_DELETE', 'Consumption Deleted')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reportaudittrail',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportaudittrail',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='reports.productionreport'),
        ),
    ]
