# Generated by Django 5.2.4 on 2025-08-23 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_machine_name_alter_machine_section'),
        ('reports', '0005_machine_section_alter_productionreport_machine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionreport',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='inventory.machine'),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='inventory.section'),
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
