# Generated by Django 5.2.5 on 2025-08-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_productionreport_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionreport',
            name='created_by',
        ),
    ]
