# Generated by Django 5.2.5 on 2025-08-28 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_remove_machine_section_and_more'),
        ('production', '0001_initial'),
        ('reports', '0008_remove_productionreport_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionreport',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='production.machine'),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='production.section'),
        ),
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=12)),
                ('raw_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_consumed', to='reports.productionreport')),
            ],
        ),
    ]
