# Generated by Django 5.2.5 on 2025-08-30 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(default='unamed item', max_length=100)),
                ('width', models.PositiveSmallIntegerField(blank=True, default=0, help_text='in mm')),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text='in meter', max_digits=10, null=True)),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='in mm', max_digits=10, null=True)),
                ('gsm', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='grams per square meter', max_digits=10, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='in kg', max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('RAW', 'Raw Material'), ('CONSUMABLE', 'Consumable'), ('WIP', 'Work In Progress'), ('FG', 'Finished Goods')], max_length=20)),
                ('uom', models.CharField(choices=[('kg', 'Kilogram'), ('m', 'Meter'), ('roll', 'Roll'), ('sheet', 'Sheet'), ('l', 'Liter'), ('carton', 'Carton')], default='kg', max_length=20)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='inventory_i_code_971ebd_idx'), models.Index(fields=['category'], name='inventory_i_categor_fe6a79_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUST', 'Adjustment'), ('TRANSFER', 'Transfer')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('finished_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_lines', to='inventory.inventoryitem')),
                ('raw_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_boms', to='inventory.inventoryitem')),
            ],
            options={
                'unique_together': {('finished_item', 'raw_item')},
            },
        ),
    ]
