# Generated by Django 5.2.5 on 2025-08-28 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_section_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('RAW', 'Raw Material'), ('CONSUMABLE', 'Consumable'), ('WIP', 'Work In Progress'), ('FG', 'Finished Goods')], max_length=20)),
                ('uom', models.CharField(choices=[('kg', 'Kilogram'), ('m', 'Meter'), ('roll', 'Roll'), ('sheet', 'Sheet'), ('l', 'Liter'), ('carton', 'Carton')], default='kg', max_length=20)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='machine',
            name='section',
        ),
        migrations.RemoveField(
            model_name='productionreport',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='productionreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productionreport',
            name='section',
        ),
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('finished_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_lines', to='inventory.inventoryitem')),
                ('raw_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_boms', to='inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUST', 'Adjustment'), ('TRANSFER', 'Transfer')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem')),
            ],
        ),
    ]
