# Generated by Django 5.2.5 on 2025-08-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_remove_machine_section_and_more'),
        ('reports', '0009_alter_productionreport_machine_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='ProductionReport',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.AlterUniqueTogether(
            name='billofmaterial',
            unique_together={('finished_item', 'raw_item')},
        ),
    ]
