# Generated by Django 5.2.5 on 2025-08-29 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_delete_machine_delete_productionreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='gsm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='grams per square meter', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in meter', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(default='unamed item', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='in kg', max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='in mm'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['code'], name='inventory_i_code_971ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category'], name='inventory_i_categor_fe6a79_idx'),
        ),
    ]
