# Generated by Django 5.2.5 on 2025-09-03 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_materialrequest'),
        ('production', '0001_initial'),
        ('reports', '0005_delete_materialconsumption'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='kg', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='inventory.inventoryitem')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='reports.productionreport')),
            ],
        ),
    ]
